name: Set up
description: Set up the Bun environment and install the project with a clean slate

branding:
  color: gray-dark
  icon: terminal

runs:
  using: composite
  steps:
    - uses: actions/setup-node@v4
      with:
        node-version: 22

    - uses: oven-sh/setup-bun@v2

    - run: bun install --frozen-lockfile
      shell: bash
