# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Andrew Garner
email: andrew@andrewgarner.com
description: >-
  Andrew Garner is a technical practitioner based in London.
url: "https://www.andrewgarner.com" # the base hostname & protocol for your site

# Build settings
assets:
  compress:
    css: true
  digest: true
plugin:
  - autoprefixer-rails
  - jekyll-assets
  - jekyll-tidy
exclude:
  - bin
  - docker-compose.yml
  - Dockerfile
  - Gemfile*
  - LICENSE
  - README.md
  - s3_website.yml
markdown: kramdown
