version: '3'

services:
  jekyll:
    command: jekyll server
    image: jekyll/jekyll:3.8
    ports:
      - '4000:4000'
    volumes:
      - ./:/srv/jekyll:cached
      - bundle:/usr/local/bundle
  s3_website:
    build: .
    volumes:
      - ./_site:/srv/s3_website/_site

volumes:
  bundle:
