version: '3'

services:
  jekyll:
    environment:
      - FORCE_BUNDLER
      - FORCE_CACHE
    image: 'jekyll/jekyll:builder'
    ports:
      - '4000:4000'
    volumes:
      - ./:/srv/jekyll:cached
      - bundle:/usr/local/bundle
  s3_website:
    build: .
    volumes:
      - ./_site:/srv/s3_website/_site

volumes:
  bundle:
