version: '3'

services:
  jekyll:
    command: jekyll server
    image: jekyll/jekyll:3.8
    ports:
      - '4000:4000'
    volumes:
      - ./:/srv/jekyll:cached
      - jekyll_bundle:/usr/local/bundle
  s3_website:
    build: .
    env_file:
      - s3_website.env
    volumes:
      - ./_site:/srv/s3_website/_site
      - s3_website_bundle:/usr/local/bundle

volumes:
  jekyll_bundle:
  s3_website_bundle: